-- Generate compile_commands.json for clangd every time the project is built
add_rules("plugin.compile_commands.autoupdate", {lsp = "clangd"})
-- Set c++ code standard: c++20
set_languages("c++20")
add_requires("sockpp")
add_requires("argparse")
add_requires("indicators")
add_requires("jsoncpp")

target("simple-ftp-server")
  set_kind("binary")
  add_includedirs("include")
  add_files("lib/*.cc")
  add_files("lib/*/*.cc")
  add_files("src/server_main.cc")
  add_packages("sockpp")
  add_packages("argparse")
  add_packages("indicators")
  add_packages("jsoncpp")
  add_defines("FTP_SERVER")
  
target("simple-ftp-client")
  set_kind("binary")
  add_includedirs("include")
  add_files("lib/*.cc")
  add_files("lib/*/*.cc")
  add_files("src/client_main.cc")
  add_packages("sockpp")
  add_packages("argparse")
  add_packages("indicators")
  add_packages("jsoncpp")
  add_defines("FTP_CLIENT")
